/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/jeremyxu2010/demo-apiserver/pkg/apis/demo/v1beta1"
	scheme "github.com/jeremyxu2010/demo-apiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FooBarOptionsesGetter has a method to return a FooBarOptionsInterface.
// A group's client should implement this interface.
type FooBarOptionsesGetter interface {
	FooBarOptionses(namespace string) FooBarOptionsInterface
}

// FooBarOptionsInterface has methods to work with FooBarOptions resources.
type FooBarOptionsInterface interface {
	Create(*v1beta1.FooBarOptions) (*v1beta1.FooBarOptions, error)
	Update(*v1beta1.FooBarOptions) (*v1beta1.FooBarOptions, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.FooBarOptions, error)
	List(opts v1.ListOptions) (*v1beta1.FooBarOptionsList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.FooBarOptions, err error)
	FooBarOptionsExpansion
}

// fooBarOptionses implements FooBarOptionsInterface
type fooBarOptionses struct {
	client rest.Interface
	ns     string
}

// newFooBarOptionses returns a FooBarOptionses
func newFooBarOptionses(c *DemoV1beta1Client, namespace string) *fooBarOptionses {
	return &fooBarOptionses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fooBarOptions, and returns the corresponding fooBarOptions object, and an error if there is any.
func (c *fooBarOptionses) Get(name string, options v1.GetOptions) (result *v1beta1.FooBarOptions, err error) {
	result = &v1beta1.FooBarOptions{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("foobaroptionses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FooBarOptionses that match those selectors.
func (c *fooBarOptionses) List(opts v1.ListOptions) (result *v1beta1.FooBarOptionsList, err error) {
	result = &v1beta1.FooBarOptionsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("foobaroptionses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fooBarOptionses.
func (c *fooBarOptionses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("foobaroptionses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a fooBarOptions and creates it.  Returns the server's representation of the fooBarOptions, and an error, if there is any.
func (c *fooBarOptionses) Create(fooBarOptions *v1beta1.FooBarOptions) (result *v1beta1.FooBarOptions, err error) {
	result = &v1beta1.FooBarOptions{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("foobaroptionses").
		Body(fooBarOptions).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fooBarOptions and updates it. Returns the server's representation of the fooBarOptions, and an error, if there is any.
func (c *fooBarOptionses) Update(fooBarOptions *v1beta1.FooBarOptions) (result *v1beta1.FooBarOptions, err error) {
	result = &v1beta1.FooBarOptions{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("foobaroptionses").
		Name(fooBarOptions.Name).
		Body(fooBarOptions).
		Do().
		Into(result)
	return
}

// Delete takes name of the fooBarOptions and deletes it. Returns an error if one occurs.
func (c *fooBarOptionses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("foobaroptionses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fooBarOptionses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("foobaroptionses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fooBarOptions.
func (c *fooBarOptionses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.FooBarOptions, err error) {
	result = &v1beta1.FooBarOptions{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("foobaroptionses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
