/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/jeremyxu2010/demo-apiserver/pkg/apis/demo/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFooBarOptionses implements FooBarOptionsInterface
type FakeFooBarOptionses struct {
	Fake *FakeDemoV1beta1
	ns   string
}

var foobaroptionsesResource = schema.GroupVersionResource{Group: "demo.jeremyxu2010.me", Version: "v1beta1", Resource: "foobaroptionses"}

var foobaroptionsesKind = schema.GroupVersionKind{Group: "demo.jeremyxu2010.me", Version: "v1beta1", Kind: "FooBarOptions"}

// Get takes name of the fooBarOptions, and returns the corresponding fooBarOptions object, and an error if there is any.
func (c *FakeFooBarOptionses) Get(name string, options v1.GetOptions) (result *v1beta1.FooBarOptions, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(foobaroptionsesResource, c.ns, name), &v1beta1.FooBarOptions{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooBarOptions), err
}

// List takes label and field selectors, and returns the list of FooBarOptionses that match those selectors.
func (c *FakeFooBarOptionses) List(opts v1.ListOptions) (result *v1beta1.FooBarOptionsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(foobaroptionsesResource, foobaroptionsesKind, c.ns, opts), &v1beta1.FooBarOptionsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.FooBarOptionsList{ListMeta: obj.(*v1beta1.FooBarOptionsList).ListMeta}
	for _, item := range obj.(*v1beta1.FooBarOptionsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fooBarOptionses.
func (c *FakeFooBarOptionses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(foobaroptionsesResource, c.ns, opts))

}

// Create takes the representation of a fooBarOptions and creates it.  Returns the server's representation of the fooBarOptions, and an error, if there is any.
func (c *FakeFooBarOptionses) Create(fooBarOptions *v1beta1.FooBarOptions) (result *v1beta1.FooBarOptions, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(foobaroptionsesResource, c.ns, fooBarOptions), &v1beta1.FooBarOptions{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooBarOptions), err
}

// Update takes the representation of a fooBarOptions and updates it. Returns the server's representation of the fooBarOptions, and an error, if there is any.
func (c *FakeFooBarOptionses) Update(fooBarOptions *v1beta1.FooBarOptions) (result *v1beta1.FooBarOptions, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(foobaroptionsesResource, c.ns, fooBarOptions), &v1beta1.FooBarOptions{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooBarOptions), err
}

// Delete takes name of the fooBarOptions and deletes it. Returns an error if one occurs.
func (c *FakeFooBarOptionses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(foobaroptionsesResource, c.ns, name), &v1beta1.FooBarOptions{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFooBarOptionses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(foobaroptionsesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.FooBarOptionsList{})
	return err
}

// Patch applies the patch and returns the patched fooBarOptions.
func (c *FakeFooBarOptionses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.FooBarOptions, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(foobaroptionsesResource, c.ns, name, data, subresources...), &v1beta1.FooBarOptions{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FooBarOptions), err
}
